Switch docker to yarn to avoid bug in npm
`npm install` consistently fails in Docker with a fairly generic
error: "cb() never called".  According to the npm project (at
https://github.com/npm/cli/wiki/%22cb()-never-called%3F--I'm-having-the-same-problem!%22)
this just means a callback never got called.  npm interprets that
as "something failed but I don't know what" and halts.

There's no way to reliably fix this bug, and npm won't do
anything about it because it's actually a class of bugs, not just
one thing.  Reporting it upstream won't help.

The solution is to switch to yarn, which proceeds with no
problems.  This patch does that.  It installs yarn (via sudo
because installing via npm triggers the callback bug), then uses
yarn to install our node packages.

One more thing: it is possible that the callback bug relates to
network flakiness inside Docker containers.  Yarn reports "There
appears to be trouble with your network connection. Retrying..."
and I know npm doesn't do well with poor network connections.
That said, I tried the docker install on several different
networks, including a decent fiber line.  This problem does not
appear to relate to the quality of the host machine's network
connection.