Pin Faker version so that we dont come across the decimal API change (#1520)
pydecimal complains about:
`TypeError: pydecimal() got an unexpected keyword argument 'min_value'`

for versions of faker < 1.0